# Generated by Django 2.0.5 on 2018-06-01 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='johndoe@example.com', max_length=1000)),
                ('password', models.CharField(default='password123', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='email',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Website'),
        ),
    ]
