# Generated by Django 2.0.5 on 2018-05-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordsecure', '0002_auto_20180530_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.CharField(default='johndoe@example.com', max_length=1000),
        ),
        migrations.AlterField(
            model_name='email',
            name='password',
            field=models.CharField(default='password123', max_length=1000),
        ),
    ]
