# Generated by Django 2.0.5 on 2018-05-30 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwordsecure', '0004_auto_20180530_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text',
            new_name='email',
        ),
    ]
