# Generated by Django 2.0.5 on 2018-05-30 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwordsecure', '0006_auto_20180530_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='website',
        ),
    ]
