# Generated by Django 2.0.5 on 2018-05-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordsecure', '0009_auto_20180530_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='password',
            field=models.CharField(default='password123', max_length=1000),
        ),
    ]
