# Generated by Django 2.0.5 on 2018-05-30 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwordsecure', '0010_email_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='votes',
        ),
    ]
