# Generated by Django 2.0.5 on 2018-06-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordsecure', '0012_auto_20180601_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='notes',
            field=models.CharField(default='N/A', max_length=2000),
        ),
    ]
